name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write # Required for deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0' # Use a stable version

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build Web
        run: |
          # The Base URL must be the exact name of your repository, enclosed in slashes (e.g., /tempp/)
          flutter build web --release --base-href /tempp/ 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages # The branch the pages will be deployed to
          enable_jekyll: true # Disable Jekyll processing
